module "aws-ecs-setup" {
  source                       = "../modules/aws-ecs-lb-scaling"
  infra_state                  = var.infra_state
  secret_store                 = var.secret_store
  state_bucket_name            = var.state_bucket_name
  infra_profile                = var.infra_profile
  region                       = var.region
  deregistration_delay         = var.deregistration_delay
  health_check_enabled         = var.health_check_enabled
  app_name                     = var.app_name
  tr_resource_owner            = var.tr_resource_owner
  timeout                      = var.timeout
  tr_environment_type          = var.tr_environment_type
  health_check_path            = var.health_check_path
  healthy_threshold            = var.healthy_threshold
  interval                     = var.interval
  listener_port                = var.listener_port
  listener_protocol            = var.listener_protocol
  ssl_policy                   = var.ssl_policy
  target_protocol              = var.target_protocol
  target_port                  = var.target_port
  target_type                  = var.target_type
  unhealthy_threshold          = var.unhealthy_threshold
  autoscaling_min_size         = var.autoscaling_min_size
  autoscaling_max_size         = var.autoscaling_max_size
  autoscaling_desired_capacity = var.autoscaling_desired_capacity
  health_check_grace_period    = var.health_check_grace_period
  associate_public_ip_address  = var.associate_public_ip_address
  aws_instance_type            = var.aws_instance_type
  image_id                     = var.image_id
  update_default_version       = var.update_default_version
  instance_log_group           = var.instance_log_group
  additional_user_data_script  = var.additional_user_data_script
}

module "aws-iam-cross-account" {
  source                       = "../modules/aws-cross-account"
  cross-account-id             = var.cross-account-id
  cross-account-role-name      = var.cross-account-role-name
  tr_resource_owner            = var.tr_resource_owner
  tr_environment_type          = var.tr_environment_type
}